webtalk_init -webtalk_dir C:/Users/Jianning/Desktop/EE2026/Week 3/lab_1_graded/lab_1_graded.sim/sim_1/behav/xsim/xsim.dir/switch_to_LED_simulation_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Jan 29 20:24:01 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "b6b5a7bb-0055-4c1b-aa63-d36632a2dcf1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "9d92e944f5fc4e6397d2c9cb5da0bf93" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "17" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2592 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.08_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6436_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3045440404 -regid "" -xml C:/Users/Jianning/Desktop/EE2026/Week 3/lab_1_graded/lab_1_graded.sim/sim_1/behav/xsim/xsim.dir/switch_to_LED_simulation_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Jianning/Desktop/EE2026/Week 3/lab_1_graded/lab_1_graded.sim/sim_1/behav/xsim/xsim.dir/switch_to_LED_simulation_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Jianning/Desktop/EE2026/Week 3/lab_1_graded/lab_1_graded.sim/sim_1/behav/xsim/xsim.dir/switch_to_LED_simulation_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
